image: python:2.7.15

pages:
  stage: deploy
  script:
  - apk update && apk add make
  - pip install -r requirements.txt
  - git clone https://github.com/getpelican/pelican-plugins.git
  - make publish
  artifacts:
    paths:
    - public/
  only:
  - master

test:
  stage: test
  script:
  - apk update && apk add make
  - pip install -r requirements.txt
  - make publish
  only:
  - branches
  except:
  - master
